config/routes.rb
Rails.application.routes.draw do

  resources :channels
  
  resources :discussions do
    resources :replies
  end 

  resources :dashboard, only: [:index]
  
  resources :articles do 
  	resources :comments 
  	member do
  		put 'like', to: "articles#like"
  		put 'unlike', to: "articles#unlike"
  	end
  end

  devise_for :users, controllers: {registrations: 'registrations' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "dashboard#index"
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :title, :article, presence: true

	extend FriendlyId
  		friendly_id :title, use: [:slugged, :finders]

  	def should_generate_new_friendly_id?
    	title_changed?
  	end  

	is_impressionable
	acts_as_votable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, only: [:edit,:update,:destroy, :like, :unlike]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order("created_at DESC")
    @article = Article.new
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @article.liked_by current_user
    respond_to do |format|
      format.html { redirect_to @article, fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  def unlike
    @article.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:article, :name, :title)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_feed.html.erb
<div class="column is-half">

<% @articles.each do | article |%>
	<%= link_to article do %>
	<div class="box">
		<article class="media">
			<div class="media-left">
				<figure class="image is-64x64">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content has-text-grey-dark">
					<strong><%= article.user.name %></strong><br/>
					<small><%= article.user.username %></small><br/>
					<p>
						<h4 class="has-text-info is-italic"><%= article.title %></h4>
						<%= raw article.article.truncate(140) %>
					</p>
				</div>
				
	    <nav class="level article-analytics">
	    	<div class="level-right">
          <div class="level-left"></div>
            <div class="level-item views data">
            	<div class="article-time">
              <%= time_ago_in_words(article.created_at) %>
            </div>
        </div>
    </div>
          <div class="level-left"></div>
          <div class="level-right">
            <div class="level-item views data">
              <%= link_to article do %>
                <span class="icon"><i class="fa fa-eye"></i></span>
                <%= @article.impressionist_count %>
              <% end %>
            </div>
            <div class="level-item comments data">
              <%= link_to article do %>
                <span class="icon"><i class="fa fa-comment"></i></span>
                 <%= article.comments.count %>
              <% end %>
            </div>

            <div class="level-item likes">
              <% if user_signed_in? %>
                
                <% if current_user.liked? article %>
                  <%= link_to unlike_article_path(article), method: :put, class: "unlike_article" do %>
                    <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                    <span class="vote_count"><%= article.get_likes.size %></span>
                  <% end %>
                <% else %>
                  <%= link_to like_article_path(article), method: :put, class: "like_article" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= article.get_likes.size %></span>
                  <% end %>
                <% end %>
              <% else %>
                  <%= link_to like_article_path(article), method: :put, class: "like_article" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= article.get_likes.size %></span>
                  <% end %>
              <% end %>

            </div>

			<% if user_signed_in? && current_user.id ==article.user_id || has_role?(:admin) %>
				<nav class="level article-analytics">
					<div class="level-right ">
					<%= link_to edit_article_path(article), class: "level-item" do %>
						<span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
					<% end %>
					<%= link_to article, method: :delete, data: { confirm: "Are you sure you want to delete this Article?"
					} do %>
						<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
					<% end %> 
				</div>
			</nav>
			<% end %>
		</div>
	</article>
</div>
<% end %>
<% end %>
</div>

app/views/articles/_follow-the-writer.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">All Writers</p>

    <% @articles.map(&:user).uniq.each do | article |%>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong><%= article.name %></strong><br/>
						<small><%= article.username %></small><br/>
					</p>
				</div>
			</div>
		</article>
	</div>
	<% end %>
</nav>
</div>


	

app/views/articles/_form.html.erb
<%= simple_form_for @article,  html: { multipart: true }  do |f|  %>
<%= f.error_notification %>

<div class="field">
      <div class="control">
      	<%= f.input :title, label: "Title", input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
    </div>
</div>

<div class="field">
  <div class="control">
    <%= f.input :article, label: "Write your article here", input_html: {class: "textarea" }, wrapper: false, label_html: 
    {class:"label"}, placeholder: "Compose a new Article...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/articles/_hero.html.erb
<% if !user_signed_in? %>
	<section class="hero is-dark">
		<div class="hero-body">
			<div class="container has-text-centered">
				<h1 class="title is-size-5">
					 <span class="has-text-grey-light">Telligent is where learners get inspired .</span>
				</h1>
				<div class="content">
					<%= link_to "Login", new_user_session_path, class: "button is-primary" %>
				</div>
			</div>
		</div>
	</section>
<% end %>

app/views/articles/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong></br>
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Articles</p>
						<p class="title is-6"><%= current_user.articles.count %></p>
					</div>
				</div>
				
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Readers</p>
						<p class="title is-6"><%= User.count %></p>
					</div>
				</div>
			</div>
		</div>
	</nav>

	<nav class="panel">
		<p class="panel-heading"> Trending</p>
    <% @articles.map(&:title).uniq.each do | article |%>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong><%= article %></strong><br/>
					</p>
				</div>
			</div>
		</article>
	</div>
	<% end %>
	</nav>
</div>

app/views/articles/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading"> Trending</p>
    <% @articles.map(&:title).uniq.each do | article |%>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong><%= article %></strong><br/>
					</p>
				</div>
			</div>
		</article>
	</div>
	<% end %>
	</nav>
</div>

app/views/articles/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Article</h1>
				<%= render 'form', article: @article %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
				<%= link_to 'cancel', articles_path, class: "button is-dark" %>
			</p>
		</div>
	</div>
</nav>

app/views/articles/index.html.erb
<%= render 'hero' %>

<section class="section">
  <div class="container">
    <div class="columns">
    	<% if user_signed_in?%>
          <%= render 'profile'%> 
    	<% else %>
      		<%= render 'trends'%>

     	<% end %>
     		<%= render 'feed' %>
      		<%= render 'follow-the-writer' %>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column">
				<h1 class="title">New Article</h1>
				<%= render 'form', article: @article %></br>
				<%= link_to 'Cancel', articles_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="section">
	<div class="container">
		<h1 class="title is-3"><%= @article.title %></h1>
		<div class="columns">
			<div class="column is-8">
				<span class="by has-text-grey-light">by</span>
				<div class="user-name has-text-weight-bold"><%= @article.user.name %></div>
				<div class="shot-time"><span class="has-text-grey-light">posted on </span><span class="has-text-weight-semibold">
					<%= verbose_date(@article.created_at) %>
				</span></div>
			</div>	
		</div>

		<div class="columns">
			<div class="column is-8">
				<div class="shot-container">

					<div class="content">
						<div class="froala-view">
						<%= @article.article.html_safe %>
						</div>
					</div>

					<% if user_signed_in? && (current_user.id == @article.user_id) || has_role?(:admin) %>		
						<div class="buttons has-addons">
							<%= link_to 'Edit', edit_article_path(@article), class: "button" %>
							<%= link_to 'Delete', article_path, class: "button", method: :delete, data: { confirm: 'Are you sure you want to delete this article?'} %>
						</div>
					<% end %>

					<section class="comments">
						<h2 class="subtitle is-5"><%= pluralize(@article.comments.count, 'Comment') %></h2>
							<%= render @article.comments %>
					   </hr>

					   <% if user_signed_in? %>
							<div class="comment-form">
								<h3 class="subtitle is-3">Write your comment here...</h3>
								<%= render 'comments/form' %>
							</div>
						<% else %>
							<div class="content"><%= link_to 'Sign in', new_user_session_path %> to leave a comment.</div>
						<% end %>
					</section>


				</div>
			</div>
			<div class="column is-3 is-offset-1">
				<div class="nav panel show-shot-analytics">
					<div class="panel-block views data">
						<span class="icon"><i class="fa fa-eye"></i></span> 
						<%= pluralize(@article.impressionist_count, 'View') %>
						</div>
					<div class="panel-block comments data">
						<span class="icon"><i class="fa fa-comment"></i></span> 
						<%= pluralize(@article.comments.count, 'Comment') %>
					   </div>
					<div class="panel-block likes data">
				 		<% if user_signed_in? %>
             	   <% if current_user.liked? @article %>
               		<%= link_to unlike_article_path(@article), method: :put, class: "unlike_article" do %>
                  		<span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                  		<span class="vote_count"><%= pluralize(@article.get_likes.size, 'Like') %></span>
                	<% end %>
              		<% else %>
                		<%= link_to like_article_path(@article), method: :put, class: "like_article" do %>
                  		<span class="icon"><i class="fa fa-heart"></i></span>
                  		<span class="vote_count"><%= pluralize(@article.get_likes.size, 'Like') %></span>
                	<% end %>
              		<% end %>
            		<% else %>
                		<%= link_to like_article_path(@article), method: :put, class: "like_article" do %>
                  		<span class="icon"><i class="fa fa-heart"></i></span>
                  		<span class="vote_count"><%= pluralize(@article.get_likes.size, 'Like') %></span>
                		<% end %>
            		<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>