config/routes.rb
Rails.application.routes.draw do

  resources :channels
  
  resources :discussions do
    resources :replies
  end 

  resources :dashboard, only: [:index]
  
  resources :articles do 
  	resources :comments 
  	member do
  		put 'like', to: "articles#like"
  		put 'unlike', to: "articles#unlike"
  	end
  end

  devise_for :users, controllers: {registrations: 'registrations' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "dashboard#index"
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>Telligent</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p> 
      </div>
    <% end %>

    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
      <% if user_signed_in? %>
        <%= link_to articles_path, class: "navbar-item" do %>
        <h1 class="title is-2 has-text-white"> Telligent </h1>
      <% end %>
      <% else %>
        <%= link_to dashboard_index_path, class: "navbar-item" do %>
        <h1 class="title is-2 has-text-white"> Telligent </h1>
        <% end %>
        <% end %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

     <div id="navbar" class="navbar-menu">
       <div class="level-left">
        <% if user_signed_in? %>
        <div class="navbar-start">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Articles', articles_path , class:"button is-dark" %>
              </p>
            </div>
          </div>
        </div>

<!--Path should be updated as the module for discussion forum is created 
       The view should be updated to shift the navbar leftwords-->
        <div class="navbar-start">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Discussion Forum', discussions_path , class:"button is-dark" %>
              </p>
            </div>
          </div>
        </div>
        <% end %>
      </div>

   
         <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
              <p class="control ">
                <div class="dropdown is-hoverable">
                  <div class="dropdown-trigger">
                    <button class="button is-info is-rounded" aria-haspopup="true" aria-controls="dropdown-menu4">
                      <span>Create New</span>
                      <span class="icon is-small">
                      <i class="fa fa-angle-down" aria-hidden="true"></i>
                      </span>
                    </button>
                  </div>
                <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                <div class="dropdown-content">
                  <div class="dropdown-item">
                    <p class="control">
                      <%= link_to new_article_path do %>
                      <span class="icon is-small"><i class="fa fa-pencil"></i></span>
                      <span>Article</span>
                      <% end %>
                    </p></br>
                    <p class="control">
                      <%= link_to new_discussion_path do %>
                      <span class="icon is-small"><i class="fa fa-group"></i></span>
                      <span>Discussion</span>
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
            </p>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info is-rounded" %>  
              </p>

              <p class="control">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info is-rounded" %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </nav>

    <%= yield %>
 
  </body>
   <footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Telligent</strong> by <a href="https://www.linkedin.com/in/ananypratap/">Ananya Pratap</a>. The source code has repository 
      <a href=https://github.com/AnanyPSS/Telligent>GitHub</a>. The website has a copyright 
      <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">ZZZZZZ.</a>.
    </p>
  </div>
</footer>
</html>